### ISSUE TITLE
SDB add_value does not work in boto 1.9b

### ISSUE THREAD

**Issue by GoogleCodeExporter** [peterknife/boto#315]
```
What steps will reproduce the problem?

1. Install boto 1.9b
2. Create 'test' item in domain 'test':
   test_item = test.new_item('test')
3. Add attr:value pair:
   test_item[u'pets'] = u'dog'
4. Attempt to add another value to 'pets' attribute:
   test_item.add_value(u'pets', u'cat')

This yields:
AttributeError: 'Item' object has no attribute 'add_value'

When using boto 1.8d add_value works as expected.

What version of the product are you using? On what operating system?
Mac OS 10.6, python 2.6


```

Original issue reported on code.google.com by `d...@jfish.org` on 5 Jan 2010 at 9:52
