### ISSUE TITLE
hashlib / sha1 / python 2.4 related problem?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [peterknife/boto#172]
```
Hello!

I'm using boto 1.5b with python 2.4.3 and hashlib-20060408a because
standard hashlib seems only available since python 2.5. I got this error:

  File "test.py", line 7, in ?
    conn = S3Connection('XXXXXXXX', 'YYYYYY')
  File "/usr/lib/python2.4/site-packages/boto/s3/connection.py", line 102,
in __init__
    https_connection_factory=https_connection_factory)
  File "/usr/lib/python2.4/site-packages/boto/connection.py", line 137, in
__init__
    self.hmac = hmac.new(self.aws_secret_access_key, digestmod=hashlib.sha1)
  File "/usr/lib64/python2.4/hmac.py", line 107, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib64/python2.4/hmac.py", line 42, in __init__
    self.outer = digestmod.new()
AttributeError: 'builtin_function_or_method' object has no attribute 'new'

I modified /usr/lib/python2.4/site-packages/boto/connection.py the
following way:
1) added import sha
2) replaced
self.hmac = hmac.new(self.aws_secret_access_key, digestmod=hashlib.sha1)
with
self.hmac = hmac.new(self.aws_secret_access_key, digestmod=sha)

After this modification it works.

It looks like this hashlib-replacement is not fully compatible. Maybe my
modification also works with python 2.5 and might be an alternative way?
I'm not a big python programmer - so please be indulgent to me if I made
totally wrong conclusions ;-)

Best regards,
Daniel
```

Original issue reported on code.google.com by `goo...@vfnm.de` on 19 Nov 2008 at 5:51
